'use client'
import { useEffect,useState } from 'react'; import { io } from 'socket.io-client'; import { API } from '../../../lib/api';
const SOCKET=process.env.NEXT_PUBLIC_SOCKET_URL||'http://localhost:4000';
const labels:any={AVAILABLE:['Disponível para atendimento','bg-emerald-600'],IN_SERVICE:['Atendimento em andamento','bg-red-600'],PAUSED:['Retorno em breve','bg-amber-500'],CLOSED:['Atendimento encerrado','bg-slate-600'],UNAVAILABLE:['Sala indisponível','bg-gray-700']};
export default function Display({params}:{params:{deviceCode:string}}){const [data,setData]=useState<any>(null); const [online,setOnline]=useState(false);
 async function load(){const r=await fetch(`${API}/api/display/${params.deviceCode}`); const j=await r.json(); setData(j); localStorage.setItem('lastDisplay:'+params.deviceCode,JSON.stringify(j))}
 useEffect(()=>{const cached=localStorage.getItem('lastDisplay:'+params.deviceCode); if(cached) setData(JSON.parse(cached)); load().catch(()=>{}); const s=io(SOCKET); s.on('connect',()=>{setOnline(true); s.emit('device:join',params.deviceCode)}); s.on('disconnect',()=>setOnline(false)); s.on('display:update',load); s.on('display:changed',load); return()=>{s.disconnect()}},[params.deviceCode]);
 const room=data?.room; const doctor=room?.doctor; const status=labels[room?.status]||labels.UNAVAILABLE;
 return <main className="min-h-screen bg-slate-950 text-white flex items-center justify-center p-8"><div className="w-full max-w-5xl rounded-[2rem] bg-white/10 border border-white/10 p-10 shadow-2xl"><div className="flex justify-between items-start mb-8"><div><p className="text-slate-300 text-2xl">{room?.name||'Sala não vinculada'}</p><h1 className="text-6xl font-black mt-2">{doctor?.name||'Sem médico vinculado'}</h1><p className="text-3xl text-slate-300 mt-3">{doctor?.specialty||''} {doctor?.crm?`• ${doctor.crm}`:''}</p></div><div className={`px-6 py-3 rounded-full text-xl ${online?'bg-emerald-700':'bg-gray-700'}`}>{online?'Online':'Offline'}</div></div><div className="grid md:grid-cols-[280px_1fr] gap-10 items-center">{doctor?.photoUrl?<img src={`${API}${doctor.photoUrl}`} className="w-72 h-72 rounded-full object-cover border-8 border-white/20"/>:<div className="w-72 h-72 rounded-full bg-white/10 grid place-items-center text-7xl">+</div>}<div><div className={`${status[1]} rounded-3xl p-10 text-center`}><p className="text-5xl font-black">{status[0]}</p></div><p className="text-center text-slate-300 text-xl mt-8">Aguarde a orientação da recepção ou do profissional responsável.</p></div></div></div></main>}
